### ISSUE TITLE
relays

### ISSUE THREAD

**Issue by soylant** [mjlodge/ortalctl#1]
Hi
what relay are you s using for the Rasberry to control the fireplace

**Comment by samf74** [comment]
![image](https://user-images.githubusercontent.com/76271657/102703813-e3f93680-4241-11eb-980b-eed237592e2e.png)

Connect the first wire to the ground, and then use the next 3 GPIO ports - 17, 27, and 22

**Comment by mjlodge** [comment]
Sorry to be slow. I used the Elegoo 4-channel 5V DC relay board.
