### ISSUE TITLE
Random triggering of the fireplace

### ISSUE THREAD

**Issue by samf74** [mjlodge/ortalctl#2]
When i have my fireplace connected to the raspberry pi as described, i have noticed that the fireplace will turn on on its own randomly. It doesnt seem like the code is running as my log files don't have any record of the trigger. 

Has anyone else experienced this? Could it be random signals on the GPIO board?

**Comment by mjlodge** [comment]
Hi, sorry for the slow (15 month!) reply. It certainly seems related to the Pi given you don't see it when it isn't connected. Is the ground (return) connection secure and working? If the relay voltages are not tied to a common ground then that could explain it.

**Comment by mjlodge** [comment]
I should have asked: you are using relays between the Pi and the control board, right? If you are driving the control board wires directly from the GPIO then you could get the behavior you describe because the PI can't handle the current and/or there is voltage drift from not having a common ground.

**Comment by samf74** [comment]
Thank you!  You're right i don't have relays. So whenever the program isn't
running, there are random signals. But there is a command to do virtual
relays i think as part of gpioinitialize. Seems to behave well as long as
it's running.

Are there any relays you'd recommend?

**Comment by mjlodge** [comment]
I used the Elegoo 4-channel relay board. It's cheap and does the job. While it does work to wire the controller directly to the Pi... for safety and reliability it is best to use relays.

**Comment by samf74** [comment]
Thank you!
